basic_settings:
  site_title: Hello, I’m Joni
  site_tagline: an excitable brand strategist
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/avatar.jpg
  logo_image:
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/'
    #- title: 'Projects'
    #  url: '/projects/'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/xyynryqo'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  mastodon_url: 'https://mastodon.yupgup.com/@joni'
  pixelfed_url: 'https://pixelfed.social/i/web/profile/659573777828622612'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  linkedin_url: 'https://www.linkedin.com/in/jonitrythall/'
  tumblr_url: 'https://apickypig.com'
  dribbble_url: 'https://dribbble.com/jonitrythall'
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/jonitrythall'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  codepen_url: ''

color_settings:
  background_color: '#FFE9D9'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#000000'
  text_medium_color: '#000000'
  text_light_color: '#592941'
  accent_color: '#305247'
  border_color: '#6C0345'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,500&display=swap" rel="stylesheet">'
  title_font: '"DM Sans", sans-serif'
  body_font: '"DM Sans", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 700
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 500
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 17
    medium_size: 19
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 700
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
